//4
// Automatically generated code. Any changes will be lost!
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.4")]
[assembly: AssemblyInformationalVersionAttribute("StagePaint 0.1.0.4 -zed'K BETA DEBUG")]

namespace StagePaint
{
    public static class Version
    {
        public const int major = 0;
        public const int minor = 1;
        public const int patch = 0;
        public const int build = 0;
        public const string Number = "0.1.0.0";
#if DEBUG
        public const string Text = Number + " -zed'K BETA DEBUG";
#else
        public const string Text = Number + " -zed'K BETA";
#endif
    }
}